create database project3;
use project3;

select * from disease;
select * from doctors;
select * from report;
select *  from patient;

--making primary key
alter table doctors add constraint pk_doctor primary key (doctor_id);
alter table patient add constraint pk_patient primary key (patient_id);

--making foreign key
alter table disease add constraint fK_doctor_id foreign key (doctor_id) references doctors;
alter table report add constraint fK_doctor_in_report foreign key (doctor_id) references doctors;
alter table report add constraint fK_patient_id foreign key (patient_id) references patient
alter table patient add constraint fK_doctor_id_patient foreign key (doctor_id) references doctors;

alter table report alter column patient_id int;

--checking for null value
select * from disease where doctor_id is null or drg_code is null or drg_definition is null or doctor_name is null;
select * from doctors where doctor_id is null or doctor_name is null or doctor_rate is null;
select * from report where patient_id is null 
or doctor_id is null 
or drg_definition is null
or first_name is null 
or last_name is null
or doctor_name is null 
or admission_date is null 
or discharge_date is null
or admitted_days is null
or discount is null 
or discount_amt is null 
or vat is null or
net_amount is null;

select * from patient where
doctor_id is null 
or patient_id is null 
or last_name is null
or first_name is null
or gender is null
or age is null
or district is null
or has_cured is null
or is_dead is null
or doctor_name is null
or drg_definition is null;

--updating the null value
update report
set net_amount =((discount_amt * 100.0) / discount) - discount_amt where discount <> 0;

update report set vat = ( net_amount - discount_amt) * 0.13;
update patient set has_cured=0 where has_cured='No';



-- to check null count
declare @sql nvarchar(max)= '';
select @sql = string_agg(
     'select ''' + column_name + ''' as columnname,
     count(*) as nullcount
     from ' + quotename(table_schema) + '.report
     where ' +quotename(column_name) +  ' is null ',
    ' union all '
)
within group (order by column_name)
from information_schema.columns
where table_name='report';

--execute the dynamic sql
exec sp_executesql @sql;



--1.Find the patient_name treated by doctor manish( same for other)?
select patient_id , first_name ,last_name from patient where doctor_name='manish';

--2.Find total number of appointments of each doctor?
select doctor_id, doctor_name, count(*) as total_appointments from report group by doctor_id,doctor_name;

--3.Find doctor with maximum appointment?
select top 1 * from (select doctor_id, doctor_name ,count(*) as total_appointments from report group by doctor_id, doctor_name)as t order by 3 desc ;

--4. Find total revenue generated by each doctor?
select doctor_id, doctor_name ,sum(net_amount) as total_revenue from report group by doctor_id,doctor_name;

--5.Find patients who visited more than one doctor?
select p.first_name,p.last_name,
count(distinct a.doctor_id) as doctor_count
from patient p
inner join report a on p.patient_id = a.patient_id
group by  p.first_name,p.last_name
having count (distinct a.doctor_id) > 1;

--6.Find most common disease?
select top  1 drg_definition,count(*) as total_cases from disease group by drg_definition order by total_cases desc;

--7.Find the total deaths per disease?
select drg_definition, count(*) AS total_deaths from patient where is_dead = 1 group by drg_definition 
order by total_deaths desc;

--8.Find patientname, doctorname and disease?
select concat( p.first_name,' ',p.last_name)as patient_name, d.doctor_name, a.drg_definition from report a
inner join patient p on a.patient_id = p.patient_id
inner join doctors d on a.doctor_id = d.doctor_id;

--9.Find patient who is dead with details?
select p.first_name,p.last_name,p.is_dead, a.drg_definition,d.doctor_name
from patient p
inner join report a on p.patient_id = a.patient_id
inner join doctors d on a.doctor_id = d.doctor_id
where p.is_dead = 1;

--10.Find totalamount generated from each district?
select p.district,sum(a.net_amount) as total_amount
from patient p
INNER JOIN report a on p.patient_id = a.patient_id
group by p.district
order by total_amount desc;